services:
  postgres-service:
    image: postgres:16
    container_name: postgres-service
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: seguranca_publica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./datasets:/datasets:ro

  pgadmin-service:
    image: dpage/pgadmin4:8
    container_name: pgadmin-service
    restart: unless-stopped
    depends_on:
      - postgres-service
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  jupyter-service:
    build:
      context: .
      dockerfile: docker/jupyter/Dockerfile
    container_name: jupyter-service
    restart: unless-stopped
    depends_on:
      - postgres-service
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: crime123
      POSTGRES_HOST: postgres-service
      POSTGRES_PORT: 5432
      POSTGRES_DB: seguranca_publica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./datasets:/home/jovyan/work/datasets
      - ./notebooks:/home/jovyan/work/notebooks
      - ./postgres-init:/home/jovyan/work/postgres-init
      - ./README.md:/home/jovyan/work/README.md:ro
    working_dir: /home/jovyan/work

  metabase-service:
    image: metabase/metabase:latest
    container_name: metabase-service
    restart: unless-stopped
    depends_on:
      - postgres-service
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  postgres_data:
